styleNames = ["Art Deco", "Art Nouveau", "Baroque", "Bauhaus & International", "Brutalist", "Byzantine", "Chicago School", "Chinese", "Deconstructivism", "Gothic", "Modernism", "Neoclassical & Beaux-Arts", "Palladian", "Postmodernism", "Romanesque", "Russian Revival"]
styleArcs = {
	"Romanesque" : [
		"Pisa Cathedral",
		"Cathedral of Monreale",
		"San Miniato al Monte",
		"Speyer Cathedral",
		"Basilica of Saint-Sernin",
		"Trier Cathedral",
		"Maria Laach Abbey",
		"Ca' Loredan",
		"Church of the Holy Sepulchre",
		"Lund Cathedral",
		"Cefalù Cathedral",
		"Parma Cathedral",
		"Vézelay Abbey",
		"Aachen Cathedral",
		"Tower of London",
		"Moissac Abbey",
		"Durham Cathedral",
		"Autun Cathedral",
		"Basilica of Sant'Ambrogio",
		"Charlemagne's Chapel"
	],
	"Gothic": [
		"Cologne Cathedral",
		"Cathedral Church of Milan",
		"Basilica of Saint-Denis",
		"Notre-Dame de Paris",
		"Canterbury Cathedral",
		"Notre-Dame de Reims",
		"Salisbury Cathedral",
		"Amiens Cathedral",
		"Chartres Cathedral",
		"Florence Cathedral",
		"St. Stephen's Cathedral",
		"Saint Vitus Cathedral",
		"Lincoln Cathedral",
		"Strasbourg Cathedral",
		"Seville Cathedral",
		"King's College Chapel",
		"Westminster Abbey",
		"Brussels Town Hall",
		"Orvieto Cathedral",
		"Jerónimos Monastery"
	],
	"Baroque": [
		"Church of the Gesù",
		"St. Peter's Basilica",
		"Palace of Versailles",
		"Karlskirche",
		"St. Paul's Cathedral",
		"Les Invalides",
		"Cathedral of Santiago de Compostela",
		"Royal Palace of Madrid",
		"Blenheim Palace",
		"Charlottenburg Palace",
		"Royal Palace of Caserta",
		"Winter Palace",
		"Santiago de Compostela Cathedral",
		"Melk Abbey",
		"Schönbrunn Palace",
		"Zwinger Palace",
		"Piazza Navona",
		"Santa Maria Maggiore",
		"Drottningholm Palace",
		"Nymphenburg Palace",
		"Mexico City Metropolitan Cathedral"
	],
	"Neoclassical & Beaux-Arts": [
		"United States Capitol",
		"El Capitolio",
		"Pantheon Paris",
		"Altes Museum",
		"Egyptian Museum",
		"General Grant National Memorial",
		"Buckingham Palace",
		"Chiswick House",
		"Kenwood House",
		"Jefferson Memorial",
		"Eglise de la Madeleine",
		"Somerset House",
		"Palais Garnier",
		"San Francisco City Hall",
		"Thomas Jefferson Building",
		"Marble House",
		"New York Public Library Main Branch",
		"Surrogate's Courthouse",
		"United States Post Office and Courthouse Texarkana",
		"Hotel Indigo Dallas Downtown",
		"Petit Palais"
	],
	"Art Nouveau": [
		"Casa Batlló",
		"Secession Building",
		"Iparművészeti Múzeum",
		"Hôtel Tassel",
		"Obecni Dum",
		"Sagrada Familia",
		"Cat House Riga",
		"Agoudas Hakehilos Synagogue",
		"Casa Milà",
		"Gresham Palace",
		"Casa Amatller",
		"Palacio de Bellas Artes",
		"Jubilee Synagogue",
		"Hotel Chile",
		"Eliseyev Emporium",
		"House with Chimaeras",
		"Horta Museum",
		"Hotel Metropol Moscow"
	],
	"Art Deco": [
		"Chrysler Building closeup",
		"Empire State Building closeup",
		"Eastern Columbia Building",
		"Hoover Building",
		"Griffith Observatory closeup",
		"Guardian Building exterior",
		"Chicago Board of Trade Building",
		"Palacio de Bellas Artes",
		"Basilica of the Sacred Heart Brussels",
		"Daily Express Building London",
		"Perelman Building",
		"Teatro Eden",
		"Brooklyn Central Library",
		"Mutual Heights",
		"Marine Air Terminal",
		"United States Custom House Philadelphia",
		"Vanity Ballroom Building",
		"Kennedy-Warren Apartment Building",
		"The Kean Building"
	],
	"Bauhaus & International": [
		"Bauhaus Dessau",
		"Bauhaus Archive",
		"Fagus Factory",
		"Masters' Houses Walter Gropius",
		"Villa Tugendhat",
		"Bauhaus Museum Dessau",
		"Haus am Horn",
		"Alan I W Frank House",
		"Bauhaus Museum Weimar",
		"Sonneveld House",
		"Museum of Modern Art exterior",
		"McGraw Hill Building",
		"Villa Stein",
		"Glaspaleis",
		"Max Liebling House",
		"Weizmann House"
	],
	"Modernism": [
		"Seagram Building",
		"Fallingwater Frank Lloyd Wright",
		"Villa Savoye",
		"Palacio da Alvorada",
		"Notre Dame du Haut",
		"Sainte Marie de La Tourette",
		"Guggenheim Museum NYC",
		"S. R. Crown Hall",
		"Villa Dirickz",
		"Neue National Galerie",
		"The Cité Radieuse",
		"Isokon Building London",
		"Salk Institute for Biological Studies",
		"John F. Kennedy Presidential Library and Museum",
		"Mesa Laboratory",
		"Dallas City Hall",
		"National Gallery East Building",
		"Phillips Exeter Academy Library"
	],
	"Postmodernism": [
		"Vanna Venturi House",
		"Portland Building",
		"Neue Staatsgalerie",
		"SIS Building",
		"James R. Thompson Center",
		"550 Madison Avenue",
		"Binoculars Building",
		"Lipstick Building",
		"TC Energy Center",
		"400 West Market",
		"PPG Place Pittsburgh",
		"Kyoto Concert Hall",
		"Denver Public Library",
		"Les Orgues de Flandre",
		"Team Disney Building",
		"Bonnefantenmuseum",
		"Piazza d'Italia",
		"Kindergarten Wolfartsweier"
	],
	"Deconstructivism": [
		"CCTV Headquarters",
		"Dancing House Prague",
		"Imperial War Museum Manchester",
		"Guggenheim Museum Bilbao",
		"Jewish Museum Berlin",
		"Walt Disney Concert Hall",
		"London Aquatics Centre",
		"Art Gallery of Ontario",
		"8 Spruce Street",
		"Beijing National Stadium",
		"Antwerp Port Office",
		"UFA cinema center",
		"Vitra fire station",
		"Museum of Pop Culture",
		"Lou Ruvo center for brain health",
		"Vitra Design Museum",
		"Seattle Central Library",
		"Wexner Centre for the Arts"
	],
	"Russian Revival": [
		"Our Lady of Iveron Cathedral",
		"Stepanov Bros. Cottage",
		"Uspenski Cathedral",
		"Kronstadt Naval Cathedral",
		"Grand Kremlin Palace",
		"Cathedral of Christ the Saviour",
		"GUM department store",
		"Sobor Aleksandra Nevskogo",
		"Polytechnical Museum",
		"Savior on the Spilled Blood",
		"Moscow Rizhsky railway station",
		"Alexander Nevsky Cathedral",
		"St. Michael's Cathedral Izhevsk",
		"Pühtitsa Convent",
		"St Nicholas Russian Orthodox Cathedral",
		"Holy Trinity Church Bolshaya Martynovka"
	],
	"Chicago School": [
		"Monadnock Building",
		"Reliance Building",
		"Chicago Savings Bank Building",
		"Guaranty Building",
		"Marquette Building",
		"Rookery Building",
		"Home Insurance Building",
		"Auditorium Building",
		"Sullivan Center",
		"Marshall Field and Company Building",
		"Railway Exchange Building",
		"Tacoma Building",
		"Toof Building",
		"Southern Methodist Publishing House",
		"Kenyon's Department Store",
		"United Brotherhood of Carpenters and Joiners-Local 132 building",
		"Redmont Hotel",
		"Manhattan Apartments",
		"Schoenhofen Brewery Historic District",
		"Ludington Building"
	],
	"Byzantine": [
		"Hagia Sophia Istanbul",
		"Basilica of Sant'apollinare Nuovo",
		"Basilica of San Vitale",
		"Basilica Cistern",
		"Basilica of Sant'Apollinare Classe",
		"Monastery of the Panocrator",
		"Our Lady of Saidnaya Monastery",
		"Hagia Sophi Trabzon",
		"Chora Church",
		"Hagia Sophia Thessaloniki",
		"Hagia Irene",
		"Hosios Loukas",
		"Daphni Monastery",
		"Church of Saint Catherine Thessaloniki",
		"Church of Holy Apostles",
		"Saint Mark's Basilica"
	],
	"Brutalist": [
		"The Breuer Building",
		"Cité Radieuse",
		"Habitat 67",
		"Boston City Hall",
		"Trellick Tower",
		"Buffalo City Court Building",
		"Western City Gate",
		"SESC Pompéia",
		"Barbican Centre and Estate",
		"Bank of London and South America",
		"Geisel Library",
		"The Met Breuer",
		"Telecommunication Center Skopje",
		"Royal National Theatre",
		"Paul Rudolph Hall",
		"Tripleone Somerset",
		"National Assembly Building Bangladesh",
		"Wotruba Church"
	],
	"Chinese": [
		"盛京宫殿",
		"故宫",
		"佛光寺东大殿",
		"西安钟楼",
		"承德避暑山庄",
		"大雁塔",
		"独乐寺",
		"晋祠",
		"奉国寺",
		"南禅寺",
		"岳阳楼",
		"白马寺",
		"天一阁",
		"六和塔",
		"华严寺",
		"孔庙"
	],
	"Palladian": [
		"Queen's House Greenwich",
		"Villa la Rotonda",
		"Leinster House",
		"Parliament House Dublin",
		"The Royal Crescent",
		"Woburn Abbey",
		"Stourhead House",
		"Holkham Hall",
		"The Rotunda University of Virginia",
		"White House",
		"Castletown House",
		"Chiswick House",
		"Kedleston Hall",
		"Belle Mont Mansion",
		"Villa Rocca Pisani"
	]
}